package com.qrcodemall.entity;

import java.io.Serializable;
import java.util.Date;

public class Carousel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_id
     *
     * @mbg.generated
     */
    private Integer carouselId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_img_name
     *
     * @mbg.generated
     */
    private String carouselImgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_link
     *
     * @mbg.generated
     */
    private String carouselLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table carousel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_id
     *
     * @return the value of carousel.carousel_id
     *
     * @mbg.generated
     */
    public Integer getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_id
     *
     * @param carouselId the value for carousel.carousel_id
     *
     * @mbg.generated
     */
    public void setCarouselId(Integer carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_img_name
     *
     * @return the value of carousel.carousel_img_name
     *
     * @mbg.generated
     */
    public String getCarouselImgName() {
        return carouselImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_img_name
     *
     * @param carouselImgName the value for carousel.carousel_img_name
     *
     * @mbg.generated
     */
    public void setCarouselImgName(String carouselImgName) {
        this.carouselImgName = carouselImgName == null ? null : carouselImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_link
     *
     * @return the value of carousel.carousel_link
     *
     * @mbg.generated
     */
    public String getCarouselLink() {
        return carouselLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_link
     *
     * @param carouselLink the value for carousel.carousel_link
     *
     * @mbg.generated
     */
    public void setCarouselLink(String carouselLink) {
        this.carouselLink = carouselLink == null ? null : carouselLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.gmt_created
     *
     * @return the value of carousel.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.gmt_created
     *
     * @param gmtCreated the value for carousel.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.gmt_modified
     *
     * @return the value of carousel.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.gmt_modified
     *
     * @param gmtModified the value for carousel.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.is_deleted
     *
     * @return the value of carousel.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.is_deleted
     *
     * @param isDeleted the value for carousel.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carousel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carouselId=").append(carouselId);
        sb.append(", carouselImgName=").append(carouselImgName);
        sb.append(", carouselLink=").append(carouselLink);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}