package com.qrcodemall.entity;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderForm implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_id
     *
     * @mbg.generated
     */
    private Integer orderFormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.user_id
     *
     * @mbg.generated
     */
    @NotNull(message = "请填写userId")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.user_address_id
     *
     * @mbg.generated
     */
    @NotNull(message = "请填写addressId")
    private Integer userAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_number
     *
     * @mbg.generated
     */
    private String orderFormNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_status
     *
     * @mbg.generated
     */
    @NotNull(message = "请填写支付状态")
    private Integer orderFormStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_price
     *
     * @mbg.generated
     */
    @NotEmpty(message = "请填写订单总价格")
    private BigDecimal orderFormPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_pay_type
     *
     * @mbg.generated
     */
    @NotNull(message = "请填写支付方式")
    private Integer orderFormPayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_form_pay_time
     *
     * @mbg.generated
     */
    private Date orderFormPayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_form
     *
     * @mbg.generated
     */
    private static final Long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_id
     *
     * @return the value of order_form.order_form_id
     *
     * @mbg.generated
     */
    public Integer getOrderFormId() {
        return orderFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_id
     *
     * @param orderFormId the value for order_form.order_form_id
     *
     * @mbg.generated
     */
    public void setOrderFormId(Integer orderFormId) {
        this.orderFormId = orderFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.user_id
     *
     * @return the value of order_form.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.user_id
     *
     * @param userId the value for order_form.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.user_address_id
     *
     * @return the value of order_form.user_address_id
     *
     * @mbg.generated
     */
    public Integer getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.user_address_id
     *
     * @param userAddressId the value for order_form.user_address_id
     *
     * @mbg.generated
     */
    public void setUserAddressId(Integer userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_number
     *
     * @return the value of order_form.order_form_number
     *
     * @mbg.generated
     */
    public String getOrderFormNumber() {
        return orderFormNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_number
     *
     * @param orderFormNumber the value for order_form.order_form_number
     *
     * @mbg.generated
     */
    public void setOrderFormNumber(String orderFormNumber) {
        this.orderFormNumber = orderFormNumber == null ? null : orderFormNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_status
     *
     * @return the value of order_form.order_form_status
     *
     * @mbg.generated
     */
    public Integer getOrderFormStatus() {
        return orderFormStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_status
     *
     * @param orderFormStatus the value for order_form.order_form_status
     *
     * @mbg.generated
     */
    public void setOrderFormStatus(Integer orderFormStatus) {
        this.orderFormStatus = orderFormStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_price
     *
     * @return the value of order_form.order_form_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderFormPrice() {
        return orderFormPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_price
     *
     * @param orderFormPrice the value for order_form.order_form_price
     *
     * @mbg.generated
     */
    public void setOrderFormPrice(BigDecimal orderFormPrice) {
        this.orderFormPrice = orderFormPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_pay_type
     *
     * @return the value of order_form.order_form_pay_type
     *
     * @mbg.generated
     */
    public Integer getOrderFormPayType() {
        return orderFormPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_pay_type
     *
     * @param orderFormPayType the value for order_form.order_form_pay_type
     *
     * @mbg.generated
     */
    public void setOrderFormPayType(Integer orderFormPayType) {
        this.orderFormPayType = orderFormPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_form_pay_time
     *
     * @return the value of order_form.order_form_pay_time
     *
     * @mbg.generated
     */
    public Date getOrderFormPayTime() {
        return orderFormPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_form_pay_time
     *
     * @param orderFormPayTime the value for order_form.order_form_pay_time
     *
     * @mbg.generated
     */
    public void setOrderFormPayTime(Date orderFormPayTime) {
        this.orderFormPayTime = orderFormPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.gmt_created
     *
     * @return the value of order_form.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.gmt_created
     *
     * @param gmtCreated the value for order_form.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.gmt_modified
     *
     * @return the value of order_form.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.gmt_modified
     *
     * @param gmtModified the value for order_form.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.is_deleted
     *
     * @return the value of order_form.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.is_deleted
     *
     * @param isDeleted the value for order_form.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderFormId=").append(orderFormId);
        sb.append(", userId=").append(userId);
        sb.append(", userAddressId=").append(userAddressId);
        sb.append(", orderFormNumber=").append(orderFormNumber);
        sb.append(", orderFormStatus=").append(orderFormStatus);
        sb.append(", orderFormPrice=").append(orderFormPrice);
        sb.append(", orderFormPayType=").append(orderFormPayType);
        sb.append(", orderFormPayTime=").append(orderFormPayTime);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}