package com.qrcodemall.entity;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;
import java.util.Date;

public class PropertyValue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.property_value_id
     *
     * @mbg.generated
     */
    private Integer propertyValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.property_id
     *
     * @mbg.generated
     */
    @NotBlank(message = "keyid不能为空")
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.qrcode_id
     *
     * @mbg.generated
     */
    @NotBlank(message = "二维码id不能为空")
    private Integer qrcodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.property_key
     *
     * @mbg.generated
     */
    @NotBlank(message = "key名字不能为空")
    private String propertyKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.property_value
     *
     * @mbg.generated
     */
    @NotBlank(message = "value不能为空")
    private String propertyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property_value
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.property_value_id
     *
     * @return the value of property_value.property_value_id
     *
     * @mbg.generated
     */
    public Integer getPropertyValueId() {
        return propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.property_value_id
     *
     * @param propertyValueId the value for property_value.property_value_id
     *
     * @mbg.generated
     */
    public void setPropertyValueId(Integer propertyValueId) {
        this.propertyValueId = propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.property_id
     *
     * @return the value of property_value.property_id
     *
     * @mbg.generated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.property_id
     *
     * @param propertyId the value for property_value.property_id
     *
     * @mbg.generated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.qrcode_id
     *
     * @return the value of property_value.qrcode_id
     *
     * @mbg.generated
     */
    public Integer getQrcodeId() {
        return qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.qrcode_id
     *
     * @param qrcodeId the value for property_value.qrcode_id
     *
     * @mbg.generated
     */
    public void setQrcodeId(Integer qrcodeId) {
        this.qrcodeId = qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.property_key
     *
     * @return the value of property_value.property_key
     *
     * @mbg.generated
     */
    public String getPropertyKey() {
        return propertyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.property_key
     *
     * @param propertyKey the value for property_value.property_key
     *
     * @mbg.generated
     */
    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey == null ? null : propertyKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.gmt_created
     *
     * @return the value of property_value.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.gmt_created
     *
     * @param gmtCreated the value for property_value.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.gmt_modified
     *
     * @return the value of property_value.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.gmt_modified
     *
     * @param gmtModified the value for property_value.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.is_deleted
     *
     * @return the value of property_value.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.is_deleted
     *
     * @param isDeleted the value for property_value.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.property_value
     *
     * @return the value of property_value.property_value
     *
     * @mbg.generated
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.property_value
     *
     * @param propertyValue the value for property_value.property_value
     *
     * @mbg.generated
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", propertyValueId=").append(propertyValueId);
        sb.append(", propertyId=").append(propertyId);
        sb.append(", qrcodeId=").append(qrcodeId);
        sb.append(", propertyKey=").append(propertyKey);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", propertyValue=").append(propertyValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}