package com.qrcodemall.entity;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import java.io.Serializable;
import java.util.Date;

public class Property implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_id
     *
     * @mbg.generated
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_key
     *
     * @mbg.generated
     */
    @NotBlank(message = "key不能为空")
    private String propertyKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.goods_type_name
     *
     * @mbg.generated
     */
    @NotBlank(message = "种类不能为空")
    private String goodsTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.goods_type_id
     *
     * @mbg.generated
     */
    @NotBlank(message = "种类id不能为空")
    private Integer goodsTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_id
     *
     * @return the value of property.property_id
     *
     * @mbg.generated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_id
     *
     * @param propertyId the value for property.property_id
     *
     * @mbg.generated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_key
     *
     * @return the value of property.property_key
     *
     * @mbg.generated
     */
    public String getPropertyKey() {
        return propertyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_key
     *
     * @param propertyKey the value for property.property_key
     *
     * @mbg.generated
     */
    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey == null ? null : propertyKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.goods_type_name
     *
     * @return the value of property.goods_type_name
     *
     * @mbg.generated
     */
    public String getGoodsTypeName() {
        return goodsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.goods_type_name
     *
     * @param goodsTypeName the value for property.goods_type_name
     *
     * @mbg.generated
     */
    public void setGoodsTypeName(String goodsTypeName) {
        this.goodsTypeName = goodsTypeName == null ? null : goodsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.goods_type_id
     *
     * @return the value of property.goods_type_id
     *
     * @mbg.generated
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.goods_type_id
     *
     * @param goodsTypeId the value for property.goods_type_id
     *
     * @mbg.generated
     */
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.gmt_created
     *
     * @return the value of property.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.gmt_created
     *
     * @param gmtCreated the value for property.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.gmt_modified
     *
     * @return the value of property.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.gmt_modified
     *
     * @param gmtModified the value for property.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.is_deleted
     *
     * @return the value of property.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.is_deleted
     *
     * @param isDeleted the value for property.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", propertyId=").append(propertyId);
        sb.append(", propertyKey=").append(propertyKey);
        sb.append(", goodsTypeName=").append(goodsTypeName);
        sb.append(", goodsTypeId=").append(goodsTypeId);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}