package com.qrcodemall.entity;

import java.io.Serializable;
import java.util.Date;

public class Qrcode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.qrcode_id
     *
     * @mbg.generated
     */
    private Integer qrcodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.goods_type_id
     *
     * @mbg.generated
     */
    private Integer goodsTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.goods_type_name
     *
     * @mbg.generated
     */
    private String goodsTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.qrcode_link
     *
     * @mbg.generated
     */
    private String qrcodeLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.qrcode_id
     *
     * @return the value of qrcode.qrcode_id
     *
     * @mbg.generated
     */
    public Integer getQrcodeId() {
        return qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.qrcode_id
     *
     * @param qrcodeId the value for qrcode.qrcode_id
     *
     * @mbg.generated
     */
    public void setQrcodeId(Integer qrcodeId) {
        this.qrcodeId = qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.user_id
     *
     * @return the value of qrcode.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.user_id
     *
     * @param userId the value for qrcode.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.goods_id
     *
     * @return the value of qrcode.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.goods_id
     *
     * @param goodsId the value for qrcode.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.goods_type_id
     *
     * @return the value of qrcode.goods_type_id
     *
     * @mbg.generated
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.goods_type_id
     *
     * @param goodsTypeId the value for qrcode.goods_type_id
     *
     * @mbg.generated
     */
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.goods_type_name
     *
     * @return the value of qrcode.goods_type_name
     *
     * @mbg.generated
     */
    public String getGoodsTypeName() {
        return goodsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.goods_type_name
     *
     * @param goodsTypeName the value for qrcode.goods_type_name
     *
     * @mbg.generated
     */
    public void setGoodsTypeName(String goodsTypeName) {
        this.goodsTypeName = goodsTypeName == null ? null : goodsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.qrcode_link
     *
     * @return the value of qrcode.qrcode_link
     *
     * @mbg.generated
     */
    public String getQrcodeLink() {
        return qrcodeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.qrcode_link
     *
     * @param qrcodeLink the value for qrcode.qrcode_link
     *
     * @mbg.generated
     */
    public void setQrcodeLink(String qrcodeLink) {
        this.qrcodeLink = qrcodeLink == null ? null : qrcodeLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.gmt_created
     *
     * @return the value of qrcode.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.gmt_created
     *
     * @param gmtCreated the value for qrcode.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.gmt_modified
     *
     * @return the value of qrcode.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.gmt_modified
     *
     * @param gmtModified the value for qrcode.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode.is_deleted
     *
     * @return the value of qrcode.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode.is_deleted
     *
     * @param isDeleted the value for qrcode.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qrcodeId=").append(qrcodeId);
        sb.append(", userId=").append(userId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsTypeId=").append(goodsTypeId);
        sb.append(", goodsTypeName=").append(goodsTypeName);
        sb.append(", qrcodeLink=").append(qrcodeLink);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}