package com.qrcodemall.entity;

import javax.validation.constraints.NotEmpty;
import java.io.Serializable;
import java.util.Date;

public class QrcodeBatch implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.qrcode_batch_id
     *
     * @mbg.generated
     */
    private Integer qrcodeBatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.qrcode_number
     *
     * @mbg.generated
     */
    @NotEmpty(message = "数量不能为空")
    private Integer qrcodeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.is_mail
     *
     * @mbg.generated
     */
    private Integer isMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.goods_type_name
     *
     * @mbg.generated
     */
    @NotEmpty(message = "种类不能为空")
    private String goodsTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.qrcode_id
     *
     * @mbg.generated
     */
    @NotEmpty(message = "二维码id不能为空")
    private Integer qrcodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.express_number
     *
     * @mbg.generated
     */
    private String expressNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.express_services_company
     *
     * @mbg.generated
     */
    private String expressServicesCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.user_address_id
     *
     * @mbg.generated
     */
    @NotEmpty(message = "用户地址id不能为空")
    private Integer userAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrcode_batch.goods_type_id
     *
     * @mbg.generated
     */
    private Integer goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.qrcode_batch_id
     *
     * @return the value of qrcode_batch.qrcode_batch_id
     *
     * @mbg.generated
     */
    public Integer getQrcodeBatchId() {
        return qrcodeBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.qrcode_batch_id
     *
     * @param qrcodeBatchId the value for qrcode_batch.qrcode_batch_id
     *
     * @mbg.generated
     */
    public void setQrcodeBatchId(Integer qrcodeBatchId) {
        this.qrcodeBatchId = qrcodeBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.user_id
     *
     * @return the value of qrcode_batch.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.user_id
     *
     * @param userId the value for qrcode_batch.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.qrcode_number
     *
     * @return the value of qrcode_batch.qrcode_number
     *
     * @mbg.generated
     */
    public Integer getQrcodeNumber() {
        return qrcodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.qrcode_number
     *
     * @param qrcodeNumber the value for qrcode_batch.qrcode_number
     *
     * @mbg.generated
     */
    public void setQrcodeNumber(Integer qrcodeNumber) {
        this.qrcodeNumber = qrcodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.is_mail
     *
     * @return the value of qrcode_batch.is_mail
     *
     * @mbg.generated
     */
    public Integer getIsMail() {
        return isMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.is_mail
     *
     * @param isMail the value for qrcode_batch.is_mail
     *
     * @mbg.generated
     */
    public void setIsMail(Integer isMail) {
        this.isMail = isMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.goods_type_name
     *
     * @return the value of qrcode_batch.goods_type_name
     *
     * @mbg.generated
     */
    public String getGoodsTypeName() {
        return goodsTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.goods_type_name
     *
     * @param goodsTypeName the value for qrcode_batch.goods_type_name
     *
     * @mbg.generated
     */
    public void setGoodsTypeName(String goodsTypeName) {
        this.goodsTypeName = goodsTypeName == null ? null : goodsTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.qrcode_id
     *
     * @return the value of qrcode_batch.qrcode_id
     *
     * @mbg.generated
     */
    public Integer getQrcodeId() {
        return qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.qrcode_id
     *
     * @param qrcodeId the value for qrcode_batch.qrcode_id
     *
     * @mbg.generated
     */
    public void setQrcodeId(Integer qrcodeId) {
        this.qrcodeId = qrcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.express_number
     *
     * @return the value of qrcode_batch.express_number
     *
     * @mbg.generated
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.express_number
     *
     * @param expressNumber the value for qrcode_batch.express_number
     *
     * @mbg.generated
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.express_services_company
     *
     * @return the value of qrcode_batch.express_services_company
     *
     * @mbg.generated
     */
    public String getExpressServicesCompany() {
        return expressServicesCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.express_services_company
     *
     * @param expressServicesCompany the value for qrcode_batch.express_services_company
     *
     * @mbg.generated
     */
    public void setExpressServicesCompany(String expressServicesCompany) {
        this.expressServicesCompany = expressServicesCompany == null ? null : expressServicesCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.user_address_id
     *
     * @return the value of qrcode_batch.user_address_id
     *
     * @mbg.generated
     */
    public Integer getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.user_address_id
     *
     * @param userAddressId the value for qrcode_batch.user_address_id
     *
     * @mbg.generated
     */
    public void setUserAddressId(Integer userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.gmt_created
     *
     * @return the value of qrcode_batch.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.gmt_created
     *
     * @param gmtCreated the value for qrcode_batch.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.gmt_modified
     *
     * @return the value of qrcode_batch.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.gmt_modified
     *
     * @param gmtModified the value for qrcode_batch.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrcode_batch.goods_type_id
     *
     * @return the value of qrcode_batch.goods_type_id
     *
     * @mbg.generated
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrcode_batch.goods_type_id
     *
     * @param goodsTypeId the value for qrcode_batch.goods_type_id
     *
     * @mbg.generated
     */
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qrcodeBatchId=").append(qrcodeBatchId);
        sb.append(", userId=").append(userId);
        sb.append(", qrcodeNumber=").append(qrcodeNumber);
        sb.append(", isMail=").append(isMail);
        sb.append(", goodsTypeName=").append(goodsTypeName);
        sb.append(", qrcodeId=").append(qrcodeId);
        sb.append(", expressNumber=").append(expressNumber);
        sb.append(", expressServicesCompany=").append(expressServicesCompany);
        sb.append(", userAddressId=").append(userAddressId);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", goodsTypeId=").append(goodsTypeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}