package com.qrcodemall.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserBillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public UserBillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserBillIdIsNull() {
            addCriterion("user_bill_id is null");
            return (Criteria) this;
        }

        public Criteria andUserBillIdIsNotNull() {
            addCriterion("user_bill_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserBillIdEqualTo(Integer value) {
            addCriterion("user_bill_id =", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdNotEqualTo(Integer value) {
            addCriterion("user_bill_id <>", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdGreaterThan(Integer value) {
            addCriterion("user_bill_id >", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_bill_id >=", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdLessThan(Integer value) {
            addCriterion("user_bill_id <", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_bill_id <=", value, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdIn(List<Integer> values) {
            addCriterion("user_bill_id in", values, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdNotIn(List<Integer> values) {
            addCriterion("user_bill_id not in", values, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdBetween(Integer value1, Integer value2) {
            addCriterion("user_bill_id between", value1, value2, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserBillIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_bill_id not between", value1, value2, "userBillId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyIsNull() {
            addCriterion("user_bill_money is null");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyIsNotNull() {
            addCriterion("user_bill_money is not null");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyEqualTo(Long value) {
            addCriterion("user_bill_money =", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyNotEqualTo(Long value) {
            addCriterion("user_bill_money <>", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyGreaterThan(Long value) {
            addCriterion("user_bill_money >", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("user_bill_money >=", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyLessThan(Long value) {
            addCriterion("user_bill_money <", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyLessThanOrEqualTo(Long value) {
            addCriterion("user_bill_money <=", value, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyIn(List<Long> values) {
            addCriterion("user_bill_money in", values, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyNotIn(List<Long> values) {
            addCriterion("user_bill_money not in", values, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyBetween(Long value1, Long value2) {
            addCriterion("user_bill_money between", value1, value2, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillMoneyNotBetween(Long value1, Long value2) {
            addCriterion("user_bill_money not between", value1, value2, "userBillMoney");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionIsNull() {
            addCriterion("user_bill_direction is null");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionIsNotNull() {
            addCriterion("user_bill_direction is not null");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionEqualTo(Integer value) {
            addCriterion("user_bill_direction =", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionNotEqualTo(Integer value) {
            addCriterion("user_bill_direction <>", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionGreaterThan(Integer value) {
            addCriterion("user_bill_direction >", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_bill_direction >=", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionLessThan(Integer value) {
            addCriterion("user_bill_direction <", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionLessThanOrEqualTo(Integer value) {
            addCriterion("user_bill_direction <=", value, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionIn(List<Integer> values) {
            addCriterion("user_bill_direction in", values, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionNotIn(List<Integer> values) {
            addCriterion("user_bill_direction not in", values, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionBetween(Integer value1, Integer value2) {
            addCriterion("user_bill_direction between", value1, value2, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillDirectionNotBetween(Integer value1, Integer value2) {
            addCriterion("user_bill_direction not between", value1, value2, "userBillDirection");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkIsNull() {
            addCriterion("user_bill_remark is null");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkIsNotNull() {
            addCriterion("user_bill_remark is not null");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkEqualTo(String value) {
            addCriterion("user_bill_remark =", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkNotEqualTo(String value) {
            addCriterion("user_bill_remark <>", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkGreaterThan(String value) {
            addCriterion("user_bill_remark >", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("user_bill_remark >=", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkLessThan(String value) {
            addCriterion("user_bill_remark <", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkLessThanOrEqualTo(String value) {
            addCriterion("user_bill_remark <=", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkLike(String value) {
            addCriterion("user_bill_remark like", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkNotLike(String value) {
            addCriterion("user_bill_remark not like", value, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkIn(List<String> values) {
            addCriterion("user_bill_remark in", values, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkNotIn(List<String> values) {
            addCriterion("user_bill_remark not in", values, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkBetween(String value1, String value2) {
            addCriterion("user_bill_remark between", value1, value2, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andUserBillRemarkNotBetween(String value1, String value2) {
            addCriterion("user_bill_remark not between", value1, value2, "userBillRemark");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bill
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}