package com.qrcodemall.entity;

import java.io.Serializable;
import java.util.Date;

public class UserAddress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_id
     *
     * @mbg.generated
     */
    private Integer userAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_province
     *
     * @mbg.generated
     */
    private String userAddressProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_city
     *
     * @mbg.generated
     */
    private String userAddressCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_district
     *
     * @mbg.generated
     */
    private String userAddressDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_detail
     *
     * @mbg.generated
     */
    private String userAddressDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_address_default
     *
     * @mbg.generated
     */
    private Integer userAddressDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receive_name
     *
     * @mbg.generated
     */
    private String receiveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receive_phone
     *
     * @mbg.generated
     */
    private String receivePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_address
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_id
     *
     * @return the value of user_address.user_address_id
     *
     * @mbg.generated
     */
    public Integer getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_id
     *
     * @param userAddressId the value for user_address.user_address_id
     *
     * @mbg.generated
     */
    public void setUserAddressId(Integer userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_province
     *
     * @return the value of user_address.user_address_province
     *
     * @mbg.generated
     */
    public String getUserAddressProvince() {
        return userAddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_province
     *
     * @param userAddressProvince the value for user_address.user_address_province
     *
     * @mbg.generated
     */
    public void setUserAddressProvince(String userAddressProvince) {
        this.userAddressProvince = userAddressProvince == null ? null : userAddressProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_city
     *
     * @return the value of user_address.user_address_city
     *
     * @mbg.generated
     */
    public String getUserAddressCity() {
        return userAddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_city
     *
     * @param userAddressCity the value for user_address.user_address_city
     *
     * @mbg.generated
     */
    public void setUserAddressCity(String userAddressCity) {
        this.userAddressCity = userAddressCity == null ? null : userAddressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_district
     *
     * @return the value of user_address.user_address_district
     *
     * @mbg.generated
     */
    public String getUserAddressDistrict() {
        return userAddressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_district
     *
     * @param userAddressDistrict the value for user_address.user_address_district
     *
     * @mbg.generated
     */
    public void setUserAddressDistrict(String userAddressDistrict) {
        this.userAddressDistrict = userAddressDistrict == null ? null : userAddressDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_detail
     *
     * @return the value of user_address.user_address_detail
     *
     * @mbg.generated
     */
    public String getUserAddressDetail() {
        return userAddressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_detail
     *
     * @param userAddressDetail the value for user_address.user_address_detail
     *
     * @mbg.generated
     */
    public void setUserAddressDetail(String userAddressDetail) {
        this.userAddressDetail = userAddressDetail == null ? null : userAddressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_address_default
     *
     * @return the value of user_address.user_address_default
     *
     * @mbg.generated
     */
    public Integer getUserAddressDefault() {
        return userAddressDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_address_default
     *
     * @param userAddressDefault the value for user_address.user_address_default
     *
     * @mbg.generated
     */
    public void setUserAddressDefault(Integer userAddressDefault) {
        this.userAddressDefault = userAddressDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.gmt_created
     *
     * @return the value of user_address.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.gmt_created
     *
     * @param gmtCreated the value for user_address.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.gmt_modified
     *
     * @return the value of user_address.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.gmt_modified
     *
     * @param gmtModified the value for user_address.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.is_deleted
     *
     * @return the value of user_address.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.is_deleted
     *
     * @param isDeleted the value for user_address.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receive_name
     *
     * @return the value of user_address.receive_name
     *
     * @mbg.generated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receive_name
     *
     * @param receiveName the value for user_address.receive_name
     *
     * @mbg.generated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receive_phone
     *
     * @return the value of user_address.receive_phone
     *
     * @mbg.generated
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receive_phone
     *
     * @param receivePhone the value for user_address.receive_phone
     *
     * @mbg.generated
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone == null ? null : receivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userAddressId=").append(userAddressId);
        sb.append(", userId=").append(userId);
        sb.append(", userAddressProvince=").append(userAddressProvince);
        sb.append(", userAddressCity=").append(userAddressCity);
        sb.append(", userAddressDistrict=").append(userAddressDistrict);
        sb.append(", userAddressDetail=").append(userAddressDetail);
        sb.append(", userAddressDefault=").append(userAddressDefault);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", receiveName=").append(receiveName);
        sb.append(", receivePhone=").append(receivePhone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}