package com.qrcodemall.entity;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("user_email is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("user_email is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("user_email =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("user_email <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("user_email >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("user_email >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("user_email <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("user_email <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("user_email like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("user_email not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("user_email in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("user_email not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("user_email between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("user_email not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andIsVipIsNull() {
            addCriterion("is_vip is null");
            return (Criteria) this;
        }

        public Criteria andIsVipIsNotNull() {
            addCriterion("is_vip is not null");
            return (Criteria) this;
        }

        public Criteria andIsVipEqualTo(Integer value) {
            addCriterion("is_vip =", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipNotEqualTo(Integer value) {
            addCriterion("is_vip <>", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipGreaterThan(Integer value) {
            addCriterion("is_vip >", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_vip >=", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipLessThan(Integer value) {
            addCriterion("is_vip <", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipLessThanOrEqualTo(Integer value) {
            addCriterion("is_vip <=", value, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipIn(List<Integer> values) {
            addCriterion("is_vip in", values, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipNotIn(List<Integer> values) {
            addCriterion("is_vip not in", values, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipBetween(Integer value1, Integer value2) {
            addCriterion("is_vip between", value1, value2, "isVip");
            return (Criteria) this;
        }

        public Criteria andIsVipNotBetween(Integer value1, Integer value2) {
            addCriterion("is_vip not between", value1, value2, "isVip");
            return (Criteria) this;
        }

        public Criteria andUserPointIsNull() {
            addCriterion("user_point is null");
            return (Criteria) this;
        }

        public Criteria andUserPointIsNotNull() {
            addCriterion("user_point is not null");
            return (Criteria) this;
        }

        public Criteria andUserPointEqualTo(Integer value) {
            addCriterion("user_point =", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointNotEqualTo(Integer value) {
            addCriterion("user_point <>", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointGreaterThan(Integer value) {
            addCriterion("user_point >", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_point >=", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointLessThan(Integer value) {
            addCriterion("user_point <", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointLessThanOrEqualTo(Integer value) {
            addCriterion("user_point <=", value, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointIn(List<Integer> values) {
            addCriterion("user_point in", values, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointNotIn(List<Integer> values) {
            addCriterion("user_point not in", values, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointBetween(Integer value1, Integer value2) {
            addCriterion("user_point between", value1, value2, "userPoint");
            return (Criteria) this;
        }

        public Criteria andUserPointNotBetween(Integer value1, Integer value2) {
            addCriterion("user_point not between", value1, value2, "userPoint");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdIsNull() {
            addCriterion("user_father_proxy_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdIsNotNull() {
            addCriterion("user_father_proxy_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdEqualTo(Integer value) {
            addCriterion("user_father_proxy_id =", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdNotEqualTo(Integer value) {
            addCriterion("user_father_proxy_id <>", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdGreaterThan(Integer value) {
            addCriterion("user_father_proxy_id >", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_father_proxy_id >=", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdLessThan(Integer value) {
            addCriterion("user_father_proxy_id <", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_father_proxy_id <=", value, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdIn(List<Integer> values) {
            addCriterion("user_father_proxy_id in", values, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdNotIn(List<Integer> values) {
            addCriterion("user_father_proxy_id not in", values, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdBetween(Integer value1, Integer value2) {
            addCriterion("user_father_proxy_id between", value1, value2, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_father_proxy_id not between", value1, value2, "userFatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameIsNull() {
            addCriterion("user_father_proxy_name is null");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameIsNotNull() {
            addCriterion("user_father_proxy_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameEqualTo(String value) {
            addCriterion("user_father_proxy_name =", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameNotEqualTo(String value) {
            addCriterion("user_father_proxy_name <>", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameGreaterThan(String value) {
            addCriterion("user_father_proxy_name >", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_father_proxy_name >=", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameLessThan(String value) {
            addCriterion("user_father_proxy_name <", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameLessThanOrEqualTo(String value) {
            addCriterion("user_father_proxy_name <=", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameLike(String value) {
            addCriterion("user_father_proxy_name like", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameNotLike(String value) {
            addCriterion("user_father_proxy_name not like", value, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameIn(List<String> values) {
            addCriterion("user_father_proxy_name in", values, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameNotIn(List<String> values) {
            addCriterion("user_father_proxy_name not in", values, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameBetween(String value1, String value2) {
            addCriterion("user_father_proxy_name between", value1, value2, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserFatherProxyNameNotBetween(String value1, String value2) {
            addCriterion("user_father_proxy_name not between", value1, value2, "userFatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdIsNull() {
            addCriterion("user_grandfather_proxy_id is null");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdIsNotNull() {
            addCriterion("user_grandfather_proxy_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdEqualTo(Integer value) {
            addCriterion("user_grandfather_proxy_id =", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdNotEqualTo(Integer value) {
            addCriterion("user_grandfather_proxy_id <>", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdGreaterThan(Integer value) {
            addCriterion("user_grandfather_proxy_id >", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_grandfather_proxy_id >=", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdLessThan(Integer value) {
            addCriterion("user_grandfather_proxy_id <", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_grandfather_proxy_id <=", value, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdIn(List<Integer> values) {
            addCriterion("user_grandfather_proxy_id in", values, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdNotIn(List<Integer> values) {
            addCriterion("user_grandfather_proxy_id not in", values, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdBetween(Integer value1, Integer value2) {
            addCriterion("user_grandfather_proxy_id between", value1, value2, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_grandfather_proxy_id not between", value1, value2, "userGrandfatherProxyId");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameIsNull() {
            addCriterion("user_grandfather_proxy_name is null");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameIsNotNull() {
            addCriterion("user_grandfather_proxy_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameEqualTo(String value) {
            addCriterion("user_grandfather_proxy_name =", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameNotEqualTo(String value) {
            addCriterion("user_grandfather_proxy_name <>", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameGreaterThan(String value) {
            addCriterion("user_grandfather_proxy_name >", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_grandfather_proxy_name >=", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameLessThan(String value) {
            addCriterion("user_grandfather_proxy_name <", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameLessThanOrEqualTo(String value) {
            addCriterion("user_grandfather_proxy_name <=", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameLike(String value) {
            addCriterion("user_grandfather_proxy_name like", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameNotLike(String value) {
            addCriterion("user_grandfather_proxy_name not like", value, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameIn(List<String> values) {
            addCriterion("user_grandfather_proxy_name in", values, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameNotIn(List<String> values) {
            addCriterion("user_grandfather_proxy_name not in", values, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameBetween(String value1, String value2) {
            addCriterion("user_grandfather_proxy_name between", value1, value2, "userGrandfatherProxyName");
            return (Criteria) this;
        }

        public Criteria andUserGrandfatherProxyNameNotBetween(String value1, String value2) {
            addCriterion("user_grandfather_proxy_name not between", value1, value2, "userGrandfatherProxyName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}