package com.qrcodemall.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_address
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_address
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_address
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public UserAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_address
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserAddressIdIsNull() {
            addCriterion("user_address_id is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdIsNotNull() {
            addCriterion("user_address_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdEqualTo(Integer value) {
            addCriterion("user_address_id =", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdNotEqualTo(Integer value) {
            addCriterion("user_address_id <>", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdGreaterThan(Integer value) {
            addCriterion("user_address_id >", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_address_id >=", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdLessThan(Integer value) {
            addCriterion("user_address_id <", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_address_id <=", value, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdIn(List<Integer> values) {
            addCriterion("user_address_id in", values, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdNotIn(List<Integer> values) {
            addCriterion("user_address_id not in", values, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdBetween(Integer value1, Integer value2) {
            addCriterion("user_address_id between", value1, value2, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserAddressIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_address_id not between", value1, value2, "userAddressId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceIsNull() {
            addCriterion("user_address_province is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceIsNotNull() {
            addCriterion("user_address_province is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceEqualTo(String value) {
            addCriterion("user_address_province =", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceNotEqualTo(String value) {
            addCriterion("user_address_province <>", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceGreaterThan(String value) {
            addCriterion("user_address_province >", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("user_address_province >=", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceLessThan(String value) {
            addCriterion("user_address_province <", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceLessThanOrEqualTo(String value) {
            addCriterion("user_address_province <=", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceLike(String value) {
            addCriterion("user_address_province like", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceNotLike(String value) {
            addCriterion("user_address_province not like", value, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceIn(List<String> values) {
            addCriterion("user_address_province in", values, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceNotIn(List<String> values) {
            addCriterion("user_address_province not in", values, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceBetween(String value1, String value2) {
            addCriterion("user_address_province between", value1, value2, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressProvinceNotBetween(String value1, String value2) {
            addCriterion("user_address_province not between", value1, value2, "userAddressProvince");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityIsNull() {
            addCriterion("user_address_city is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityIsNotNull() {
            addCriterion("user_address_city is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityEqualTo(String value) {
            addCriterion("user_address_city =", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityNotEqualTo(String value) {
            addCriterion("user_address_city <>", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityGreaterThan(String value) {
            addCriterion("user_address_city >", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityGreaterThanOrEqualTo(String value) {
            addCriterion("user_address_city >=", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityLessThan(String value) {
            addCriterion("user_address_city <", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityLessThanOrEqualTo(String value) {
            addCriterion("user_address_city <=", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityLike(String value) {
            addCriterion("user_address_city like", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityNotLike(String value) {
            addCriterion("user_address_city not like", value, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityIn(List<String> values) {
            addCriterion("user_address_city in", values, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityNotIn(List<String> values) {
            addCriterion("user_address_city not in", values, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityBetween(String value1, String value2) {
            addCriterion("user_address_city between", value1, value2, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressCityNotBetween(String value1, String value2) {
            addCriterion("user_address_city not between", value1, value2, "userAddressCity");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictIsNull() {
            addCriterion("user_address_district is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictIsNotNull() {
            addCriterion("user_address_district is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictEqualTo(String value) {
            addCriterion("user_address_district =", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictNotEqualTo(String value) {
            addCriterion("user_address_district <>", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictGreaterThan(String value) {
            addCriterion("user_address_district >", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("user_address_district >=", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictLessThan(String value) {
            addCriterion("user_address_district <", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictLessThanOrEqualTo(String value) {
            addCriterion("user_address_district <=", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictLike(String value) {
            addCriterion("user_address_district like", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictNotLike(String value) {
            addCriterion("user_address_district not like", value, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictIn(List<String> values) {
            addCriterion("user_address_district in", values, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictNotIn(List<String> values) {
            addCriterion("user_address_district not in", values, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictBetween(String value1, String value2) {
            addCriterion("user_address_district between", value1, value2, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDistrictNotBetween(String value1, String value2) {
            addCriterion("user_address_district not between", value1, value2, "userAddressDistrict");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailIsNull() {
            addCriterion("user_address_detail is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailIsNotNull() {
            addCriterion("user_address_detail is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailEqualTo(String value) {
            addCriterion("user_address_detail =", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailNotEqualTo(String value) {
            addCriterion("user_address_detail <>", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailGreaterThan(String value) {
            addCriterion("user_address_detail >", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailGreaterThanOrEqualTo(String value) {
            addCriterion("user_address_detail >=", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailLessThan(String value) {
            addCriterion("user_address_detail <", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailLessThanOrEqualTo(String value) {
            addCriterion("user_address_detail <=", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailLike(String value) {
            addCriterion("user_address_detail like", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailNotLike(String value) {
            addCriterion("user_address_detail not like", value, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailIn(List<String> values) {
            addCriterion("user_address_detail in", values, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailNotIn(List<String> values) {
            addCriterion("user_address_detail not in", values, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailBetween(String value1, String value2) {
            addCriterion("user_address_detail between", value1, value2, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDetailNotBetween(String value1, String value2) {
            addCriterion("user_address_detail not between", value1, value2, "userAddressDetail");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultIsNull() {
            addCriterion("user_address_default is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultIsNotNull() {
            addCriterion("user_address_default is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultEqualTo(Integer value) {
            addCriterion("user_address_default =", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultNotEqualTo(Integer value) {
            addCriterion("user_address_default <>", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultGreaterThan(Integer value) {
            addCriterion("user_address_default >", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_address_default >=", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultLessThan(Integer value) {
            addCriterion("user_address_default <", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultLessThanOrEqualTo(Integer value) {
            addCriterion("user_address_default <=", value, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultIn(List<Integer> values) {
            addCriterion("user_address_default in", values, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultNotIn(List<Integer> values) {
            addCriterion("user_address_default not in", values, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultBetween(Integer value1, Integer value2) {
            addCriterion("user_address_default between", value1, value2, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andUserAddressDefaultNotBetween(Integer value1, Integer value2) {
            addCriterion("user_address_default not between", value1, value2, "userAddressDefault");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andReceiveNameIsNull() {
            addCriterion("receive_name is null");
            return (Criteria) this;
        }

        public Criteria andReceiveNameIsNotNull() {
            addCriterion("receive_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveNameEqualTo(String value) {
            addCriterion("receive_name =", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameNotEqualTo(String value) {
            addCriterion("receive_name <>", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameGreaterThan(String value) {
            addCriterion("receive_name >", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameGreaterThanOrEqualTo(String value) {
            addCriterion("receive_name >=", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameLessThan(String value) {
            addCriterion("receive_name <", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameLessThanOrEqualTo(String value) {
            addCriterion("receive_name <=", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameLike(String value) {
            addCriterion("receive_name like", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameNotLike(String value) {
            addCriterion("receive_name not like", value, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameIn(List<String> values) {
            addCriterion("receive_name in", values, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameNotIn(List<String> values) {
            addCriterion("receive_name not in", values, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameBetween(String value1, String value2) {
            addCriterion("receive_name between", value1, value2, "receiveName");
            return (Criteria) this;
        }

        public Criteria andReceiveNameNotBetween(String value1, String value2) {
            addCriterion("receive_name not between", value1, value2, "receiveName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_address
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_address
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}