apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  selector:
    matchLabels:
      project: mysql8
  replicas: 1
  template:
    metadata:
      labels:
        project: mysql8
    spec:
      containers:
        - image: mysql:8.0
          name: mysql8
          ports:
          - containerPort: 3306
            name: mysql8
          env:
          - name: root
            value: "18842332832"
