apiVersion: v1 # v1是service的apiversion
kind: Service # 当前资源的类型为 Service。
metadata:
  name: qrcodemall-front-admin-service # Service 的名字
spec:
  type: NodePort
  selector:
    project: qrcodemall-front-admin
  ports:
    - name: http
      port: 32556 #集群内布访问的端口
      targetPort: 80 #容器端口
      nodePort: 32556 #开放给外部的端口