apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcodemall-server
spec:
  selector:
    matchLabels:
      project: qrcodemall-server
  replicas: 3
  template:
    metadata:
      labels:
        project: qrcodemall-server
    spec:
      containers:
        - name: qrcodemall-server
          image: cpeony/qrcodemall_backend:1.0
          ports:
            - containerPort: 32557
