apiVersion: v1 # v1是service的apiversion
kind: Service # 当前资源的类型为 Service。
metadata:
  name: rabbitmq-service # Service 的名字
spec:
  selector:
    project: rabbitmq
  type: NodePort
  ports:
    - name: rabbit15672
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: rabbit5672
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: rabbit4369
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: rabbit25672
      port: 25672
      protocol: TCP
      targetPort: 25672
    - name: rabbit5671
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: rabbit15671
      port: 15671
      protocol: TCP
      targetPort: 15671