apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      project: redis
  replicas: 1
  template:
    metadata:
      labels:
        project: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
