apiVersion: v1 # v1是service的apiversion
kind: Service # 当前资源的类型为 Service。
metadata:
  name: redis-service # Service 的名字
spec:
  type: NodePort
  selector: # elector 指明挑选那些 label 为 run: httpd 的 Pod 作为 Service 的后端。
    project: redis
  ports: # 将 Service 的 8080 端口映射到 Pod 的 80 端口，使用 TCP 协议。
    - name: http
      port: 6379
      targetPort: 6379

