package com.qrcodemall.dao;

import com.qrcodemall.entity.OrderFormDetail;
import com.qrcodemall.entity.OrderFormDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderFormDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    long countByExample(OrderFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int deleteByExample(OrderFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderFormDeatilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int insert(OrderFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int insertSelective(OrderFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    List<OrderFormDetail> selectByExample(OrderFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    OrderFormDetail selectByPrimaryKey(Integer orderFormDeatilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderFormDetail record, @Param("example") OrderFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderFormDetail record, @Param("example") OrderFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_form_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderFormDetail record);
}