package com.qrcodemall.dao;

import com.qrcodemall.entity.PropertyValue;
import com.qrcodemall.entity.PropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    long countByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int deleteByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer propertyValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    List<PropertyValue> selectByExampleWithBLOBs(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    PropertyValue selectByPrimaryKey(Integer propertyValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PropertyValue record);
}