package com.qrcodemall.dao;

import com.qrcodemall.entity.Qrcode;
import com.qrcodemall.entity.QrcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    long countByExample(QrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int deleteByExample(QrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer qrcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int insert(Qrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int insertSelective(Qrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    List<Qrcode> selectByExample(QrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    Qrcode selectByPrimaryKey(Integer qrcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Qrcode record, @Param("example") QrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Qrcode record, @Param("example") QrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Qrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Qrcode record);
}