package com.qrcodemall.dao;

import com.qrcodemall.entity.QrcodeBatch;
import com.qrcodemall.entity.QrcodeBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrcodeBatchMapper {

    Integer insertList(List<QrcodeBatch> qrcodeBatches);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    long countByExample(QrcodeBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int deleteByExample(QrcodeBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer qrcodeBatchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int insert(QrcodeBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int insertSelective(QrcodeBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    List<QrcodeBatch> selectByExample(QrcodeBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    QrcodeBatch selectByPrimaryKey(Integer qrcodeBatchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QrcodeBatch record, @Param("example") QrcodeBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QrcodeBatch record, @Param("example") QrcodeBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QrcodeBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrcode_batch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QrcodeBatch record);
}