package com.qrcodemall.dao;

import com.qrcodemall.entity.UserBill;
import com.qrcodemall.entity.UserBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    long countByExample(UserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int deleteByExample(UserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int insert(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int insertSelective(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    List<UserBill> selectByExample(UserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    UserBill selectByPrimaryKey(Integer userBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBill record, @Param("example") UserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBill record, @Param("example") UserBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBill record);
}